# Generated by Django 3.2 on 2023-01-24 12:06

import apps.account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Краткий заголовок структуры в компании', max_length=150, verbose_name='Заголовок')),
                ('block', models.CharField(blank=True, help_text='Название блока в компании', max_length=250, null=True, verbose_name='Блок')),
                ('department', models.CharField(blank=True, help_text='Название департамента в компании', max_length=250, null=True, verbose_name='Департамент')),
                ('group', models.CharField(blank=True, db_index=True, help_text='Название отдела в компании', max_length=250, null=True, verbose_name='Отдел')),
                ('branch', models.CharField(blank=True, db_index=True, help_text='Название группы в компании', max_length=250, null=True, verbose_name='Группа')),
                ('description', models.CharField(blank=True, help_text='Описание структуры в компании', max_length=150, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Подразделение пользователя',
                'verbose_name_plural': 'Подразделения пользователей',
                'db_table': 'content"."user_department',
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(help_text='Статус пользователя до 50 символов', max_length=50, unique=True, verbose_name='Статус')),
                ('title', models.CharField(help_text='Описание статуса пользователя до 50 символов', max_length=50, verbose_name='Описание')),
                ('description', models.TextField(blank=True, help_text='Бизнес логика статуса.', max_length=250, null=True, verbose_name='Полное описание')),
            ],
            options={
                'verbose_name': 'Статус пользователя',
                'verbose_name_plural': 'Статусы пользователей',
                'db_table': 'content"."user_status',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Заполняется автоматически системой.', primary_key=True, serialize=False, unique=True, verbose_name='UUID пользователя')),
                ('avatar', models.ImageField(default='system/user-dummy-img.jpg', upload_to=apps.account.models.generate_avatar_path)),
                ('last_name', models.CharField(blank=True, help_text='До 50 символов.', max_length=50, null=True, verbose_name='Фамилия пользователя')),
                ('first_name', models.CharField(blank=True, help_text='До 50 символов.', max_length=50, null=True, verbose_name='Имя пользователя')),
                ('middle_name', models.CharField(blank=True, help_text='До 50 символов.', max_length=50, null=True, verbose_name='Отчество пользователя')),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Основной контактный номер.', max_length=128, null=True, region=None, verbose_name='Номер мобильного телефона')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Любой номер телефона.', max_length=128, null=True, region=None, verbose_name='Номер телефона')),
                ('description', models.TextField(blank=True, help_text='Дополнительная информация', null=True, verbose_name='Примечание к профилю')),
                ('experience_start', models.DateField(blank=True, null=True, verbose_name='Дата начала работы')),
                ('experience_now', models.DateField(blank=True, null=True, verbose_name='Дата окончания работы.')),
                ('experience_description', models.TextField(blank=True, null=True, verbose_name='Обязанности.')),
                ('post', models.CharField(blank=True, help_text='Должность пользователя.', max_length=150, null=True, verbose_name='Должность')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('department', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_department', to='account.userdepartment', verbose_name='Отдел пользователя в компании')),
                ('status', models.ForeignKey(blank=True, default=1, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_status', to='account.userstatus', verbose_name='Статус пользователя в системе.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'db_table': 'content"."user_profile',
                'ordering': ['last_name'],
                'get_latest_by': 'created_time',
                'unique_together': {('user', 'last_name'), ('user', 'uuid')},
            },
        ),
    ]
